// sp3ctr-zone :: the button wall
//
// Eleventy exposes this file as `buttons` in every template. Only one thing
// reads it: the section at the bottom of src/index.njk.
//
// WHY THE LISTS ARE HERE AND THE IMAGES AREN'T
//
// The GIFs live in buttons/ at the repo root and are copied to the build
// untouched (see .eleventy.js). Nothing here knows how to draw a button — mine
// are generated by make-buttons.py, and everyone else's were made by whoever
// made them. This file is only the wall: what hangs on it, in what order, and
// where each one points.
//
// HOW TO ADD ONE
//
//  1. Save the GIF into buttons/. Save it — don't point `file` at someone
//     else's server. A hotlinked button spends their bandwidth on every load of
//     this page, breaks the day they reorganise their site, and hands them a log
//     line for every visitor who comes here. Keeping a local copy is most of the
//     etiquette of the form, and it's the same argument this site makes about
//     everything else: hold your own files.
//  2. Add a line to the right list below.
//
// Fields: `file` is the name inside buttons/, `alt` is what a screen reader and
// a broken-image box get, and `href` is optional — leave it off for a button
// that's a statement rather than a door.

// The canonical origin — the live hostname, confirmed. Used for the link target
// in the copy-paste snippet and for the download command next to it, so it's
// stated once here and nowhere else.
const ORIGIN = "https://sp3ctr-zone.neocities.org";

const HERO = "sp3ctr-zone.gif";

module.exports = {
  origin: ORIGIN,
  hero: HERO,

  // The two versions of this site's own link button. Same wordmark, and the
  // still is a real alternative rather than a fallback — see make-buttons.py.
  mine: [
    {
      file: HERO,
      alt: "sp3ctr-zone",
      note: "animated",
    },
    {
      file: "sp3ctr-zone-static.gif",
      alt: "sp3ctr-zone",
      note: "no motion",
    },
  ],

  // Statements, not links, so no href. Take them if you agree with them.
  badges: [
    { file: "trust-but-verify.gif", alt: "trust but verify" },
    { file: "view-source.gif", alt: "view source" },
    { file: "encrypt-everything.gif", alt: "encrypt everything" },
    { file: "privacy-is-a-right.gif", alt: "privacy is a right" },
    { file: "they-cant-stop-us-all.gif", alt: "can't stop us all" },
  ],

  // Sites run by people I actually know. An empty wall is more honest than a
  // padded one, so this stays empty until there's something real on it.
  //
  //   { file: "their-button.gif", href: "https://example.org/", alt: "example" },
  friends: [],

  // Buttons picked up around the web. Same rule as above: the file is saved into
  // buttons/, and `href` goes to the site it belongs to — a button is a link
  // back to somewhere, and one that points nowhere is just a sticker.
  //
  //   { file: "somewhere.gif", href: "https://somewhere.example/", alt: "somewhere" },
  collected: [],

  // What a visitor copies. The two URLs in it are deliberately different kinds,
  // and that asymmetry is the whole point of the snippet:
  //
  //   href  absolute, to this site. It's a link here; it has to resolve from
  //         wherever they are.
  //   src   a bare filename, pointing at *their* copy of the GIF sitting next to
  //         their page. Not this server.
  //
  // The src used to be absolute too, which quietly made the snippet do the exact
  // thing the paragraph above it tells people not to: every visitor to their page
  // fetched the button from here. A visitor who follows instructions shouldn't end
  // up hotlinking because the example did.
  //
  // width/height are spelled out so the button doesn't reflow their page as it
  // loads — the same reason the wall itself sets them.
  embed:
    `<a href="${ORIGIN}/">` +
    `<img src="${HERO}" width="88" height="31" alt="sp3ctr-zone">` +
    `</a>`,
};
